development:
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 906066809801-j3cpo2m5rntc4o4cqg4451uk36n7g7fk.apps.googleusercontent.com
  google_client_secret: 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

test:
  secret_key_base: here_goes_my_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>